version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - env
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
  name: nva-frontend