version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

    commands:
      - npm install

  build:
    commands:
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

cache:
  paths:
    - '/node_modules/**/*'

artifacts:
  files:
    - '**/*'
    - packaged.yaml

