AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nva-publication-channels

  Sample SAM Template for nva-publication-channels

Globals:
  Function:
    Timeout: 3

Parameters:
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  CustomDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Custom API to connect this lambda to
    Default: CustomDomain
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: publication-channels

Resources:
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
  PublicationChannelsApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/nva-publication-channels.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration: REGIONAL
  GetJournalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: channels.journal
      Runtime: nodejs14.x
      Events:
        GetJournalEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /journal
            Method: get
            RestApiId:
              Ref: PublicationChannelsApi
  GetPublisherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: channels.publisher
      Runtime: nodejs14.x
      Events:
        GetPublisherEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /publisher
            Method: get
            RestApiId:
              Ref: PublicationChannelsApi
  SearchChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: channels.searchHandler
      Runtime: nodejs14.x
      Events:
        FindChannel:
          Type: Api
          Properties:
            Path: /search
            Method: POST
            RestApiId:
              Ref: PublicationChannelsApi
            RequestModel:
              Model: Search
          type: object
          required:
            - tableId
            - searchTerm
          properties:
            tableId:
              type: integer
            searchTerm:
              type: string
            Required: true

  ChannelsBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Sub api.${CustomDomain}
      BasePath: !Ref CustomDomainBasePath
      RestApiId: !Ref PublicationChannelsApi
      Stage: !Ref PublicationChannelsApi.Stage
