AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nva-publication-channels

  Sample SAM Template for nva-publication-channels

Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: 'GET,OPTIONS'
      AllowHeaders: 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
      AllowOrigin: '*'

Parameters:
  CustomDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Custom API to connect this lambda to
    Default: CustomDomain
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: publication-channels

Resources:
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
  PublicationChannelsApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/nva-publication-channels.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration: REGIONAL
  PublicationChannelsHandler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: handler.handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          DOMAIN:  !Sub api.${CustomDomain}
          BASEPATH: !Ref CustomDomainBasePath
      Events:
        GetJournalEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId:
              Ref: PublicationChannelsApi

  ChannelsBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Sub api.${CustomDomain}
      BasePath: !Ref CustomDomainBasePath
      RestApiId: !Ref PublicationChannelsApi
      Stage: !Ref PublicationChannelsApi.Stage
