openapi: 3.0.1
info:
  title: NVA Publication Channels
  description: This is NVA Publication Channels API.
  termsOfService: http://nva.unit.no/terms/
  contact:
    email: nva@unit.no
  license:
    name: MIT
  version: 1.0.0
externalDocs:
  description: Find out more about NVA
  url: https://nva.unit.no
servers:
- url: https://api.nva.unit.no/channels
paths:
  /journal/{pid}:
    get:
      x-amazon-apigateway-integration:
        uri:
            Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetJournalFunction.Arn}/invocations
        httpMethod: POST
        type: "AWS_PROXY"
      tags:
      - Journal
      summary: Find journal by ID
      description: Returns a single Journal specified by id
      operationId: GetJournalById
      parameters:
      - name: pid
        in: path
        description: ID of journal to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicationChannel'
        400:
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        404:
          description: Journal not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /publisher/{pid}:
    get:
      x-amazon-apigateway-integration:
        uri:
            Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPublisherFunction.Arn}/invocations
        httpMethod: POST
        type: "AWS_PROXY"
      tags:
      - Publisher
      summary: Find publisher by ID
      description: Returns a single Publisher
      operationId: getPublisherById
      parameters:
      - name: pid
        in: path
        description: ID of publisher to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicationChannel'
        400:
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        404:
          description: Journal not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /search:
    post:
      x-amazon-apigateway-integration:
        uri:
            Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchChannelFunction.Arn}/invocations
        httpMethod: POST
        type: "AWS_PROXY"
      tags:
      - Channel
      summary: SearchChannelFunction search format a publication channel channel
      description: Returns a list of publication channels matching criteria
      operationId: SearchChannelFunctionChannels
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicationChannel'
        404:
          description: Channel not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    PublicationChannel:
      type: object
      properties:
        '@context':
          type: string
        id:
          type: string
        type:
          type: string
        name:
          type: string
        identifier:
          type: string
        eIssn:
          type: string
        issn:
          type: string
          format: nullable
        active:
          type: boolean
        language:
          type: string
        url:
          type: string
        publisher:
          type: string
        npiDomain:
          type: string
        scientificValue:
          type: string
    Problem:
      type: object
      properties:
        status:
          type: integer
          format: int32
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
