openapi: 3.0.1
info:
  title: NVA Publication Channels
  description: This is NVA Publication Channels API.
  termsOfService: http://nva.unit.no/terms/
  contact:
    email: nva@unit.no
  license:
    name: MIT
  version: 1.0.0
externalDocs:
  description: Find out more about NVA
  url: https://nva.unit.no
servers:
- url: https://api.nva.unit.no/channels
paths:
  /journal:
    get:
      x-amazon-apigateway-integration:
        uri:
            Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JournalFunction.Arn}/invocations
        httpMethod: POST
        type: "AWS_PROXY"
      tags:
      - Journal
      summary: List journals
      description: Returns a list of journals
      operationId: ListJournals
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journal'
        400:
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        404:
          description: Journal not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /journal/{pid}:
    get:
      x-amazon-apigateway-integration:
        uri:
            Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JournalFunction.Arn}/invocations
        httpMethod: POST
        type: "AWS_PROXY"
      tags:
      - Journal
      summary: Find journal by ID
      description: Returns a single Journal
      operationId: GetJournalById
      parameters:
      - name: pid
        in: path
        description: ID of journal to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journal'
        400:
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        404:
          description: Journal not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /publisher:
    get:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:884807050265:function:PublisherFunction/invocations"
        httpMethod: POST
        type: "AWS_PROXY"
      tags:
      - Publisher
      summary: List publishers
      description: Returns a list of publishers
      operationId: ListPublishers
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publisher'
        400:
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        404:
          description: Journal not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /publisher/{pid}:
    get:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:884807050265:function:PublisherFunction/invocations"
        httpMethod: POST
        type: "AWS_PROXY"
      tags:
      - Publisher
      summary: Find publisher by ID
      description: Returns a single Publisher
      operationId: getPublisherById
      parameters:
      - name: pid
        in: path
        description: ID of publisher to return
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Publisher'
        400:
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        404:
          description: Journal not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    Journal:
      type: object
      properties:
        '@context':
          type: string
        id:
          type: string
        name:
          type: string
        identifier:
          type: string
        eIssn:
          type: string
        issn:
          type: string
          format: nullable
        active:
          type: boolean
        language:
          type: string
        url:
          type: string
        publisher:
          type: string
        npiDomain:
          type: string
        scientificValue:
          type: string
    Publisher:
      type: object
      properties:
        '@context':
          type: string
        id:
          type: string
        name:
          type: string
        identifier:
          type: string
        isbnPrefixes:
          type: array
          items:
            type: string
        webpage:
          type: string
        active:
          type: boolean
        scientificValue:
          type: string
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
