openapi: "3.0.1"
info:
  title: "sg-publication-channels-pl-nva-publication-channels"
  description: "This is NVA Publication Channels API."
  termsOfService: "http://nva.unit.no/terms/"
  contact:
    email: "nva@unit.no"
  license:
    name: "MIT"
  version: "1.0"
externalDocs:
  description: "Find out more about NVA"
  url: "https://nva.unit.no"
servers:
- url: "https://api.dev.nva.aws.unit.no/{basePath}"
  variables:
    basePath:
      default: "/publication-channels"
paths:
  /journal:
    get:
      tags:
      - "Journal"
      summary: "List journals"
      description: "Returns a list of journals"
      security:
      - CognitoAuthorizer: []
    options:
      summary: "CORS support"
      responses:
        "200":
          description: "Default response for CORS method"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      security:
      - CognitoAuthorizer: []
  /publication:
    get:
      security:
      - CognitoAuthorizer: []
    options:
      summary: "CORS support"
      responses:
        "200":
          description: "Default response for CORS method"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      security:
      - CognitoAuthorizer: []
  /publisher:
    get:
      tags:
      - "Publisher"
      summary: "List publishers"
      description: "Returns a list of publishers"
      security:
      - CognitoAuthorizer: []
    options:
      summary: "CORS support"
      responses:
        "200":
          description: "Default response for CORS method"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      security:
      - CognitoAuthorizer: []
components:
  securitySchemes:
    CognitoAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
