name: Node.js CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: npm install
    - run: npm ci --prefix src
    - run: npm run build --if-present --prefix src
    - run: npm test  --prefix src
    - run: npm run coverage  --prefix src
    - name: codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: src/coverage/cobertura-coverage.xml

